const diseaseList = ['Common Cold', 'Influenza', 'Malaria', 'Diabetes', 'Hypertension', 'Asthma', 'Pneumonia', 'Bronchitis', 'Tuberculosis', 'HIV/AIDS', 'Heart Disease', 'Stroke', 'Cancer', 'Arthritis', 'Dengue Fever', 'Typhoid Fever', 'Cholera', 'Gastroenteritis', 'Peptic Ulcer Disease', 'Epilepsy', "Alzheimer's Disease", "Parkinson's Disease", 'Schizophrenia', 'Bipolar Disorder', 'Depression', 'Anxiety Disorders', 'Osteoporosis', 'Rheumatoid Arthritis', 'Gout', 'Chronic Kidney Disease', 'Liver Disease', 'Cirrhosis', 'Hepatitis', 'Multiple Sclerosis', 'Cystic Fibrosis', 'Chronic Obstructive Pulmonary Disease (COPD)', 'Sleep Apnea', 'Obesity', 'Anemia', 'Sickle Cell Disease', 'Glaucoma', 'Cataracts', 'Macular Degeneration', 'Chronic Fatigue Syndrome', 'Fibromyalgia', 'Lupus', "Crohn's Disease", 'Ulcerative Colitis', 'Diverticulitis', 'Gallstones', 'Pancreatitis', 'Endometriosis', 'Polycystic Ovary Syndrome (PCOS)', 'Menstrual Disorders', 'Erectile Dysfunction', 'Premature Ejaculation', 'Infertility', 'Prostate Disease', 'Endocrine Disorders', 'Thyroid Disorders', "Addison's Disease", "Cushing's Syndrome", 'Osteoarthritis', 'Scoliosis', 'Herniated Disc', 'Sciatica', 'Fibroids', 'Breast Cancer', 'Cervical Cancer', 'Prostate Cancer', 'Testicular Cancer', 'Ovarian Cancer', 'Uterine Cancer', 'Skin Cancer', 'Melanoma', 'Psoriasis', 'Eczema', 'Acne', 'Rosacea', 'Vitiligo', 'Hives', 'Allergic Rhinitis', 'Sinusitis', 'Tonsillitis', 'Pharyngitis', 'Strep Throat', 'Laryngitis', 'Conjunctivitis', 'Keratitis', 'Corneal Ulcers', 'Retinal Detachment', 'Macular Edema', 'Retinitis Pigmentosa', 'Otitis Media', 'Ear Infections', 'Tinnitus', 'Vertigo', 'Motion Sickness', 'Gastritis', 'Esophagitis', "Barrett's Esophagus", 'Gastroesophageal Reflux Disease (GERD)', 'Diverticulosis', 'Hemorrhoids', 'Irritable Bowel Syndrome (IBS)', 'Constipation', 'Diarrhea', 'Colitis', 'Appendicitis', 'Liver Cancer', 'Gallbladder Disease', 'Pancreatic Cancer', 'Food Poisoning', 'Botulism', 'Salmonella Infection', 'E. coli Infection', 'Listeria Infection', 'Norovirus Infection', 'Giardiasis', 'Cryptosporidiosis', 'Toxoplasmosis', 'Trichinosis', 'Tapeworm Infection', 'Roundworm Infection', 'Meningitis', 'Encephalitis', 'Brain Abscess', 'Guillain-Barré Syndrome', "Huntington's Disease", 'Amyotrophic Lateral Sclerosis (ALS)', 'Muscular Dystrophy', 'Myasthenia Gravis', "Bell's Palsy", 'Tourette Syndrome', 'Obsessive-Compulsive Disorder (OCD)', 'Post-Traumatic Stress Disorder (PTSD)', 'Attention Deficit Hyperactivity Disorder (ADHD)', 'Autism Spectrum Disorder (ASD)', 'Intellectual Disability', 'Down Syndrome', 'Asperger Syndrome', 'Fetal Alcohol Syndrome (FAS)', 'Major Depressive Disorder (MDD)', 'Panic Disorder', 'Phobias', 'Generalized Anxiety Disorder (GAD)', 'Social Anxiety Disorder', 'Agoraphobia', 'Eating Disorders', 'Anorexia Nervosa', 'Bulimia Nervosa', 'Binge Eating Disorder', 'Substance Use Disorders', 'Alcohol Use Disorder', 'Drug Abuse', 'Nicotine Addiction', 'Gambling Disorder', 'Internet Addiction', 'Sexual Disorders', 'Hypoactive Sexual Desire Disorder (HSDD)', 'Female Sexual Arousal Disorder', 'Vaginismus', 'Dyspareunia', 'Paraphilic Disorders', 'Pedophilic Disorder', 'Exhibitionistic Disorder', 'Fetishistic Disorder', 'Voyeuristic Disorder', 'Frotteuristic Disorder', 'Sexual Masochism Disorder', 'Sexual Sadism Disorder', 'Gender Dysphoria', 'Transvestic Disorder', 'Personality Disorders', 'Antisocial Personality Disorder', 'Borderline Personality Disorder', 'Narcissistic Personality Disorder', 'Histrionic Personality Disorder', 'Avoidant Personality Disorder', 'Dependent Personality Disorder', 'Obsessive-Compulsive Personality Disorder', 'Schizoid Personality Disorder', 'Schizotypal Personality Disorder', 'Paranoid Personality Disorder', 'Dissociative Disorders', 'Dissociative Identity Disorder', 'Dissociative Amnesia', 'Depersonalization/Derealization Disorder', 'Somatic Symptom Disorders', 'Illness Anxiety Disorder', 'Conversion Disorder', 'Factitious Disorder', 'Feeding and Eating Disorders', 'Pica', 'Rumination Disorder', 'Avoidant/Restrictive Food Intake Disorder (ARFID)', 'Elimination Disorders', 'Encopresis', 'Enuresis', 'Sleep-Wake Disorders', 'Insomnia Disorder', 'Hypersomnolence Disorder', 'Narcolepsy', 'Breathing-Related Sleep Disorders', 'Obstructive Sleep Apnea', 'Central Sleep Apnea', 'Circadian Rhythm Sleep-Wake Disorders', 'Parasomnias', 'Nightmare Disorder', 'Sleep Terror Disorder', 'Sleepwalking Disorder', 'Restless Legs Syndrome', 'Bruxism', 'Non-Rapid Eye Movement Sleep Arousal Disorders', 'Sleep-Related Eating Disorder', 'Recurrent Isolated Sleep Paralysis', 'Recurrent Hypersomnia', 'Persistent Sleep-Related Hypoventilation', 'Other Sleep Disorders', 'Sexually Transmitted Infections (STIs)', 'Chlamydia', 'Gonorrhea', 'Syphilis', 'Genital Herpes', 'Genital Warts', 'Hepatitis B', 'Hepatitis C', 'Human Papillomavirus (HPV)', 'Trichomoniasis', 'Bacterial Vaginosis', 'Yeast Infections', 'Pelvic Inflammatory Disease (PID)', 'Genital Candidiasis', 'Urinary Tract Infections (UTIs)', 'Bladder Infections', 'Kidney Infections', 'Urethritis', 'Vaginitis', 'Prostatitis', 'Herpes Zoster (Shingles)', 'Varicella (Chickenpox)', 'Measles', 'Mumps', 'Rubella (German Measles)', 'Mononucleosis (Mono)', 'Infectious Mononucleosis', 'Hand, Foot, and Mouth Disease', 'Scarlet Fever', 'Roseola', 'Fifth Disease', 'Whooping Cough', 'Croup', 'Respiratory Syncytial Virus (RSV)', 'Tuberculosis (TB)', 'Hantavirus Pulmonary Syndrome (HPS)', 'SARS (Severe Acute Respiratory Syndrome)', 'MERS (Middle East Respiratory Syndrome)', 'COVID-19'];

const diseaseInfo = {
    "Common Cold": ["Paracetamol", "Ibuprofen", "Ascorbic Acid"],
    "Influenza": ["Oseltamivir", "Zanamivir", "Acetaminophen"],
    "Malaria": ["Chloroquine", "Artemether", "Doxycycline"],
    "Diabetes": ["Insulin", "Metformin", "Gliclazide"],
    "Hypertension": ["Hydrochlorothiazide", "Metoprolol", "Enalapril"],
    "Asthma": ["Albuterol", "Fluticasone", "Montelukast"],
    "Pneumonia": ["Amoxicillin", "Ceftriaxone", "Azithromycin"],
    "Bronchitis": ["Amoxicillin", "Azithromycin", "Ceftriaxone"],
    "Tuberculosis": ["Isoniazid", "Rifampin", "Ethambutol"],
    "HIV/AIDS": ["Tenofovir", "Lamivudine", "Efavirenz"],
    "Heart Disease": ["Aspirin", "Clopidogrel", "Atorvastatin"],
    "Stroke": ["Tissue Plasminogen Activator", "Clopidogrel", "Aspirin"],
    "Cancer": ["Cisplatin", "Paclitaxel", "Tamoxifen"],
    "Arthritis": ["Acetaminophen", "Ibuprofen", "Naproxen"],
    "Dengue Fever": ["Acetaminophen", "Ibuprofen", "Fluid Replacement Therapy"],
    "Typhoid Fever": ["Ciprofloxacin", "Ceftriaxone", "Azithromycin"],
    "Cholera": ["Oral Rehydration Solution", "Azithromycin", "Doxycycline"],
    "Gastroenteritis": ["Oral Rehydration Solution", "Loperamide", "Ondansetron"],
    "Peptic Ulcer Disease": ["Proton Pump Inhibitors", "H2 Blockers", "Antibiotics"],
    "Epilepsy": ["Carbamazepine", "Valproate", "Lamotrigine"],
    "Alzheimer's Disease": ["Donepezil", "Rivastigmine", "Memantine"],
    "Parkinson's Disease": ["Levodopa", "Carbidopa", "Ropinirole"],
    "Schizophrenia": ["Risperidone", "Quetiapine", "Aripiprazole"],
    "Bipolar Disorder": ["Lithium", "Valproate", "Quetiapine"],
    "Depression": ["Selective Serotonin Reuptake Inhibitors", "Serotonin-Norepinephrine Reuptake Inhibitors", "Tricyclic Antidepressants"],
    "Anxiety Disorders": ["Selective Serotonin Reuptake Inhibitors", "Benzodiazepines", "Buspirone"],
    "Osteoporosis": ["Bisphosphonates", "Calcitonin", "Raloxifene"],
    "Rheumatoid Arthritis": ["Methotrexate", "Hydroxychloroquine", "Sulfasalazine"],
    "Gout": ["Colchicine", "Allopurinol", "Febuxostat"],
    "Chronic Kidney Disease": ["Angiotensin-Converting Enzyme Inhibitors", "Angiotensin II Receptor Blockers", "Diuretics"],
    "Liver Disease": ["Ursodeoxycholic Acid", "Silymarin", "N-acetylcysteine"],
    "Cirrhosis": ["Diuretics", "Beta-blockers", "Antibiotics"],
    "Hepatitis": ["Interferon", "Ribavirin", "Sofosbuvir"],
    "Multiple Sclerosis": ["Interferon Beta", "Glatiramer Acetate", "Fingolimod"],
    "Cystic Fibrosis": ["Bronchodilators", "Mucolytics", "Antibiotics"],
    "Chronic Obstructive Pulmonary Disease (COPD)": ["Bronchodilators", "Inhaled Corticosteroids", "Phosphodiesterase-4 Inhibitors"],
    "Sleep Apnea": ["Continuous Positive Airway Pressure (CPAP)", "Oral Appliances", "Surgery"],
    "Obesity": ["Orlistat", "Phentermine-Topiramate", "Liraglutide"],
    "Anemia": ["Iron Supplements", "Vitamin B12 Supplements", "Erythropoiesis-Stimulating Agents"],
    "Sickle Cell Disease": ["Hydroxyurea", "L-glutamine", "Blood Transfusions"],
    "Glaucoma": ["Prostaglandin Analogs", "Beta-blockers", "Alpha Agonists"],
    "Cataracts": ["No specific medications", "Surgery"],
    "Macular Degeneration": ["Anti-VEGF Agents", "Photodynamic Therapy", "Laser Surgery"],
    "Chronic Fatigue Syndrome": ["Cognitive Behavioral Therapy", "Graded Exercise Therapy", "Antidepressants"],
    "Fibromyalgia": ["Pregabalin", "Duloxetine", "Milnacipran"],
    "Lupus": ["Hydroxychloroquine", "Corticosteroids", "Immunosuppressants"],
    "Crohn's Disease": ["5-Aminosalicylates", "Corticosteroids", "Immunomodulators"],
    "Ulcerative Colitis": ["5-Aminosalicylates", "Corticosteroids", "Immunomodulators"],
    "Diverticulitis": ["Antibiotics", "Pain Medications", "Dietary Changes"],
    "Gallstones": ["Ursodeoxycholic Acid", "Chenodeoxycholic Acid", "Cholecystectomy"],
    "Pancreatitis": ["Pain Medications", "Antibiotics", "IV Fluids"],
    "Endometriosis": ["Nonsteroidal Anti-Inflammatory Drugs", "Hormonal Therapies", "Surgery"],
    "Polycystic Ovary Syndrome (PCOS)": ["Oral Contraceptives", "Metformin", "Clomiphene Citrate"],
    "Menstrual Disorders": ["Oral Contraceptives", "Nonsteroidal Anti-Inflammatory Drugs", "Hormonal Therapies"],
    "Erectile Dysfunction": ["Sildenafil", "Tadalafil", "Vardenafil"],
    "Premature Ejaculation": ["Selective Serotonin Reuptake Inhibitors", "Tricyclic Antidepressants", "Topical Anesthetics"],
    "Infertility": ["Clomiphene Citrate", "Gonadotropins", "In vitro Fertilization (IVF)"],
    "Prostate Disease": ["Alpha-blockers", "5-alpha Reductase Inhibitors", "Phosphodiesterase-5 Inhibitors"],
    "Endocrine Disorders": ["Hormone Replacement Therapy", "Insulin", "Antithyroid Medications"],
    "Thyroid Disorders": ["Levothyroxine", "Methimazole", "Propylthiouracil"],
    "Addison's Disease": ["Glucocorticoids", "Mineralocorticoids", "DHEA"],
    "Cushing's Syndrome": ["Surgery", "Mifepristone", "Ketoconazole"],
    "Osteoarthritis": ["Acetaminophen", "NSAIDs", "Topical Creams"],
    "Scoliosis": ["Bracing", "Surgery", "Physical Therapy"],
    "Herniated Disc": ["NSAIDs", "Muscle Relaxants", "Physical Therapy"],
    "Sciatica": ["NSAIDs", "Muscle Relaxants", "Physical Therapy"],
    "Fibroids": ["Gonadotropin-releasing Hormone Agonists", "Nonsteroidal Anti-Inflammatory Drugs", "Surgery"],
    "Breast Cancer": ["Tamoxifen", "Aromatase Inhibitors", "Chemotherapy"],
    "Cervical Cancer": ["Cisplatin", "Paclitaxel", "Radiation Therapy"],
    "Prostate Cancer": ["Leuprolide", "Bicalutamide", "Docetaxel"],
    "Testicular Cancer": ["Cisplatin", "Etoposide", "Bleomycin"],
    "Ovarian Cancer": ["Carboplatin", "Paclitaxel", "Bevacizumab"],
    "Uterine Cancer": ["Hysterectomy", "Chemotherapy", "Radiation Therapy"],
    "Skin Cancer": ["Surgery", "Chemotherapy", "Immunotherapy"],
    "Melanoma": ["Immunotherapy", "Targeted Therapy", "Chemotherapy"],
    "Psoriasis": ["Topical Corticosteroids", "Topical Retinoids", "Topical Vitamin D Analogues"],
    "Eczema": ["Topical Corticosteroids", "Topical Calcineurin Inhibitors", "Moisturizers"],
    "Acne": ["Benzoyl Peroxide", "Topical Retinoids", "Topical Antibiotics"],
    "Rosacea": ["Topical Metronidazole", "Azelaic Acid", "Oral Antibiotics"],
    "Vitiligo": ["Topical Corticosteroids", "Topical Calcineurin Inhibitors", "Narrowband UVB Therapy"],
    "Hives": ["Antihistamines", "Corticosteroids", "Epinephrine"],
    "Allergic Rhinitis": ["Antihistamines", "Intranasal Corticosteroids", "Decongestants"],
    "Sinusitis": ["Saline Nasal Irrigation", "Intranasal Corticosteroids", "Decongestants"],
    "Tonsillitis": ["Antibiotics", "Pain Relievers", "Oral Analgesics"],
    "Pharyngitis": ["Antibiotics", "Pain Relievers", "Throat Lozenges"],
    "Strep Throat": ["Antibiotics", "Pain Relievers", "Throat Lozenges"],
    "Laryngitis": ["Rest", "Hydration", "Humidification"],
    "Conjunctivitis": ["Artificial Tears", "Antihistamine Eye Drops", "Antibiotic Eye Drops"],
    "Glaucoma": ["Prostaglandin Analogs", "Beta-blockers", "Alpha Agonists"],
    "Keratitis": ["Antibiotic Eye Drops", "Antiviral Eye Drops", "Corticosteroid Eye Drops"],
    "Corneal Ulcers": ["Antibiotic Eye Drops", "Antifungal Eye Drops", "Antiviral Eye Drops"],
    "Retinal Detachment": ["Surgery", "Laser Therapy", "Cryotherapy"],
    "Macular Edema": ["Anti-VEGF Agents", "Corticosteroids", "Laser Therapy"],
    "Retinitis Pigmentosa": ["Vitamin A Palmitate", "Docosahexaenoic Acid", "Lutein"],
    "Otitis Media": ["Antibiotics", "Pain Relievers", "Ear Drops"],
    "Ear Infections": ["Antibiotics", "Pain Relievers", "Ear Drops"],
    "Tinnitus": ["Hearing Aids", "Cognitive Behavioral Therapy", "Sound Therapy"],
    "Vertigo": ["Antihistamines", "Benzodiazepines", "Motion Sickness Medications"],
    "Motion Sickness": ["Antihistamines", "Scopolamine", "Ginger"],
    "Gastritis": ["Antacids", "H2 Blockers", "Proton Pump Inhibitors"],
    "Esophagitis": ["Proton Pump Inhibitors", "H2 Blockers", "Antacids"],
    "Barrett's Esophagus": ["Proton Pump Inhibitors", "H2 Blockers", "Antacids"],
    "Gastroesophageal Reflux Disease (GERD)": ["Proton Pump Inhibitors", "H2 Blockers", "Antacids"],
    "Peptic Ulcer Disease": ["Proton Pump Inhibitors", "H2 Blockers", "Antibiotics"],
    "Diverticulosis": ["High-fiber Diet", "Fiber Supplements", "Hydration"],
    "Diverticulitis": ["Antibiotics", "Clear Liquid Diet", "Pain Relievers"],
    "Hemorrhoids": ["Fiber Supplements", "Topical Hemorrhoid Treatments", "Sitz Baths"],
    "Irritable Bowel Syndrome (IBS)": ["Fiber Supplements", "Antispasmodic Medications", "Laxatives"],
    "Constipation": ["Fiber Supplements", "Osmotic Laxatives", "Stool Softeners"],
    "Diarrhea": ["Fluid Replacement Therapy", "Antidiarrheal Medications", "Bismuth Subsalicylate"],
    "Colitis": ["Anti-inflammatory Medications", "Immunosuppressants", "Antibiotics"],
    "Appendicitis": ["Appendectomy", "Antibiotics", "Pain Relievers"],
    "Hepatitis": ["Interferon", "Ribavirin", "Sofosbuvir"],
    "Cirrhosis": ["Diuretics", "Beta-blockers", "Antibiotics"],
    "Liver Cancer": ["Surgery", "Chemotherapy", "Liver Transplant"],
    "Gallbladder Disease": ["Cholecystectomy", "Pain Medications", "Antibiotics"],
    "Pancreatitis": ["Pain Medications", "Antibiotics", "IV Fluids"],
    "Pancreatic Cancer": ["Surgery", "Chemotherapy", "Radiation Therapy"],
    "Food Poisoning": ["Fluid Replacement Therapy", "Antibiotics", "Antiemetics"],
    "Botulism": ["Botulinum Antitoxin", "Antibiotics", "Supportive Care"],
    "Salmonella Infection": ["Fluid Replacement Therapy", "Antibiotics", "Anti-diarrheal Medications"],
    "E. coli Infection": ["Fluid Replacement Therapy", "Antibiotics", "Supportive Care"],
    "Listeria Infection": ["Antibiotics", "Supportive Care", "IV Fluids"],
    "Norovirus Infection": ["Fluid Replacement Therapy", "Antiemetics", "Supportive Care"],
    "Giardiasis": ["Antibiotics", "Fluid Replacement Therapy", "Anti-diarrheal Medications"],
    "Cryptosporidiosis": ["Antiparasitic Medications", "Fluid Replacement Therapy", "Supportive Care"],
    "Toxoplasmosis": ["Antiparasitic Medications", "Antibiotics", "Supportive Care"],
    "Trichinosis": ["Antiparasitic Medications", "Corticosteroids", "Supportive Care"],
    "Tapeworm Infection": ["Antiparasitic Medications", "Praziquantel", "Albendazole"],
    "Roundworm Infection": ["Antiparasitic Medications", "Mebendazole", "Albendazole"],
    "Meningitis": ["Antibiotics", "Antiviral Medications", "Corticosteroids"],
    "Encephalitis": ["Antiviral Medications", "Corticosteroids", "Supportive Care"],
    "Brain Abscess": ["Antibiotics", "Surgery", "Corticosteroids"],
    "Guillain-Barré Syndrome": ["IV Immunoglobulin", "Plasmapheresis", "Supportive Care"],
    "Multiple Sclerosis": ["Interferon Beta", "Glatiramer Acetate", "Fingolimod"],
    "Huntington's Disease": ["Tetrabenazine", "Antipsychotics", "Antidepressants"],
    "Amyotrophic Lateral Sclerosis (ALS)": ["Riluzole", "Edaravone", "Baclofen"],
    "Muscular Dystrophy": ["Physical Therapy", "Bracing", "Corticosteroids"],
    "Myasthenia Gravis": ["Cholinesterase Inhibitors", "Immunosuppressants", "Thymectomy"],
    "Bell's Palsy": ["Corticosteroids", "Antiviral Medications", "Physical Therapy"],
    "Tourette Syndrome": ["Antipsychotics", "Alpha-2 Adrenergic Agonists", "Behavioral Therapy"],
    "Obsessive-Compulsive Disorder (OCD)": ["Selective Serotonin Reuptake Inhibitors", "Tricyclic Antidepressants", "Cognitive Behavioral Therapy"],
    "Post-Traumatic Stress Disorder (PTSD)": ["Selective Serotonin Reuptake Inhibitors", "Serotonin-Norepinephrine Reuptake Inhibitors", "Cognitive Behavioral Therapy"],
    "Attention Deficit Hyperactivity Disorder (ADHD)": ["Stimulants", "Nonstimulants", "Behavioral Therapy"],
    "Autism Spectrum Disorder (ASD)": ["Applied Behavior Analysis", "Occupational Therapy", "Speech Therapy"],
    "Intellectual Disability": ["Behavioral Therapy", "Educational Support", "Speech Therapy"],
    "Down Syndrome": ["Early Intervention Programs", "Educational Support", "Speech Therapy"],
    "Asperger Syndrome": ["Behavioral Therapy", "Social Skills Training", "Cognitive Behavioral Therapy"],
    "Fetal Alcohol Syndrome (FAS)": ["Behavioral Therapy", "Occupational Therapy", "Speech Therapy"],
    "Schizophrenia": ["Risperidone", "Quetiapine", "Aripiprazole"],
    "Bipolar Disorder": ["Lithium", "Valproate", "Quetiapine"],
    "Major Depressive Disorder (MDD)": ["Selective Serotonin Reuptake Inhibitors", "Serotonin-Norepinephrine Reuptake Inhibitors", "Tricyclic Antidepressants"],
    "Anxiety Disorders": ["Selective Serotonin Reuptake Inhibitors", "Benzodiazepines", "Buspirone"],
    "Panic Disorder": ["Selective Serotonin Reuptake Inhibitors", "Benzodiazepines", "Cognitive Behavioral Therapy"],
    "Phobias": ["Cognitive Behavioral Therapy", "Exposure Therapy", "Medications (for specific phobias)"],
    "Generalized Anxiety Disorder (GAD)": ["Selective Serotonin Reuptake Inhibitors", "Serotonin-Norepinephrine Reuptake Inhibitors", "Buspirone"],
    "Social Anxiety Disorder": ["Selective Serotonin Reuptake Inhibitors", "Serotonin-Norepinephrine Reuptake Inhibitors", "Beta-blockers"],
    "Agoraphobia": ["Cognitive Behavioral Therapy", "Exposure Therapy", "Medications (for panic attacks)"],
    "Post-Traumatic Stress Disorder (PTSD)": ["Selective Serotonin Reuptake Inhibitors", "Serotonin-Norepinephrine Reuptake Inhibitors", "Cognitive Behavioral Therapy"],
    "Eating Disorders": ["Cognitive Behavioral Therapy", "Nutritional Counseling", "Medications (for binge eating disorder)"],
    "Anorexia Nervosa": ["Nutritional Rehabilitation", "Psychotherapy", "Antidepressants"],
    "Bulimia Nervosa": ["Cognitive Behavioral Therapy", "Antidepressants", "Nutritional Counseling"],
    "Binge Eating Disorder": ["Cognitive Behavioral Therapy", "Antidepressants", "Nutritional Counseling"],
    "Substance Use Disorders": ["Cognitive Behavioral Therapy", "Motivational Enhancement Therapy", "Medications (for specific substances)"],
    "Alcohol Use Disorder": ["Cognitive Behavioral Therapy", "Motivational Enhancement Therapy", "Disulfiram"],
    "Drug Abuse": ["Cognitive Behavioral Therapy", "Motivational Enhancement Therapy", "Buprenorphine"],
    "Nicotine Addiction": ["Nicotine Replacement Therapy", "Bupropion", "Varenicline"],
    "Gambling Disorder": ["Cognitive Behavioral Therapy", "Motivational Enhancement Therapy", "Naltrexone"],
    "Internet Addiction": ["Cognitive Behavioral Therapy", "Medications (for specific symptoms)", "Family Therapy"],
    "Sexual Disorders": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Erectile Dysfunction": ["Sildenafil", "Tadalafil", "Vardenafil"],
    "Premature Ejaculation": ["Selective Serotonin Reuptake Inhibitors", "Tricyclic Antidepressants", "Topical Anesthetics"],
    "Hypoactive Sexual Desire Disorder (HSDD)": ["Cognitive Behavioral Therapy", "Psychotherapy", "Bremelanotide"],
    "Female Sexual Arousal Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Estrogen Therapy"],
    "Vaginismus": ["Cognitive Behavioral Therapy", "Pelvic Floor Therapy", "Dilators"],
    "Dyspareunia": ["Cognitive Behavioral Therapy", "Pelvic Floor Therapy", "Topical Estrogen"],
    "Paraphilic Disorders": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Pedophilic Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Exhibitionistic Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Fetishistic Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Voyeuristic Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Frotteuristic Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Sexual Masochism Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Sexual Sadism Disorder": ["Cognitive Behavioral Therapy", "Psychotherapy", "Medications (for specific disorders)"],
    "Gender Dysphoria": ["Psychotherapy", "Hormone Therapy", "Gender-affirming Surgery"],
    "Transvestic Disorder": ["Psychotherapy", "Couples Therapy", "Medications (for comorbid conditions)"],
    "Personality Disorders": ["Psychotherapy", "Medications (for specific symptoms)", "Dialectical Behavior Therapy"],
    "Antisocial Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for comorbid conditions)"],
    "Borderline Personality Disorder": ["Dialectical Behavior Therapy", "Psychotherapy", "Medications (for specific symptoms)"],
    "Narcissistic Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Group Therapy"],
    "Histrionic Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Group Therapy"],
    "Avoidant Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Group Therapy"],
    "Dependent Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Support Groups"],
    "Obsessive-Compulsive Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for specific symptoms)"],
    "Schizoid Personality Disorder": ["Psychotherapy", "Support Groups", "Social Skills Training"],
    "Schizotypal Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Antipsychotics"],
    "Paranoid Personality Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Supportive Therapy"],
    "Dissociative Disorders": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for specific symptoms)"],
    "Dissociative Identity Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Hypnotherapy"],
    "Dissociative Amnesia": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for specific symptoms)"],
    "Depersonalization/Derealization Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for specific symptoms)"],
    "Somatic Symptom Disorders": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for specific symptoms)"],
    "Illness Anxiety Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Antidepressants"],
    "Conversion Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Physical Therapy"],
    "Factitious Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Medications (for specific symptoms)"],
    "Feeding and Eating Disorders": ["Psychotherapy", "Nutritional Counseling", "Medications (for specific symptoms)"],
    "Pica": ["Psychotherapy", "Cognitive Behavioral Therapy", "Behavioral Interventions"],
    "Rumination Disorder": ["Psychotherapy", "Cognitive Behavioral Therapy", "Behavioral Interventions"],
    "Avoidant/Restrictive Food Intake Disorder (ARFID)": ["Psychotherapy", "Nutritional Counseling", "Behavioral Interventions"],
    "Elimination Disorders": ["Psychotherapy", "Behavioral Interventions", "Medications (for specific symptoms)"],
    "Encopresis": ["Psychotherapy", "Behavioral Interventions", "Laxatives"],
    "Enuresis": ["Psychotherapy", "Behavioral Interventions", "Desmopressin"],
    "Sleep-Wake Disorders": ["Sleep Hygiene Education", "Cognitive Behavioral Therapy", "Medications (for specific disorders)"],
    "Insomnia Disorder": ["Cognitive Behavioral Therapy", "Stimulus Control Therapy", "Sleep Restriction Therapy"],
    "Hypersomnolence Disorder": ["Cognitive Behavioral Therapy", "Stimulant Medications", "Modafinil"],
    "Narcolepsy": ["Stimulant Medications", "Sodium Oxybate", "Selective Serotonin Reuptake Inhibitors"],
    "Breathing-Related Sleep Disorders": ["Continuous Positive Airway Pressure (CPAP)", "Oral Appliances", "Surgery"],
    "Obstructive Sleep Apnea": ["Continuous Positive Airway Pressure (CPAP)", "Oral Appliances", "Surgery"],
    "Central Sleep Apnea": ["Continuous Positive Airway Pressure (CPAP)", "Adaptive Servo-Ventilation (ASV)", "Bilevel Positive Airway Pressure (BiPAP)"],
    "Circadian Rhythm Sleep-Wake Disorders": ["Light Therapy", "Chronotherapy", "Melatonin"],
    "Parasomnias": ["Cognitive Behavioral Therapy", "Safety Measures", "Medications (for specific disorders)"],
    "Nightmare Disorder": ["Cognitive Behavioral Therapy", "Imagery Rehearsal Therapy", "Prazosin"],
    "Sleep Terror Disorder": ["Cognitive Behavioral Therapy", "Scheduled Awakenings", "Benzodiazepines"],
    "Sleepwalking Disorder": ["Cognitive Behavioral Therapy", "Scheduled Awakenings", "Safety Measures"],
    "Restless Legs Syndrome": ["Dopamine Agonists", "Alpha-2 Delta Ligands", "Iron Supplements"],
    "Bruxism": ["Dental Devices", "Behavioral Therapy", "Medications (for specific symptoms)"],
    "Non-Rapid Eye Movement Sleep Arousal Disorders": ["Cognitive Behavioral Therapy", "Safety Measures", "Medications (for specific disorders)"],
    "Sleep-Related Eating Disorder": ["Cognitive Behavioral Therapy", "Safety Measures", "Medications (for specific disorders)"],
    "Recurrent Isolated Sleep Paralysis": ["Cognitive Behavioral Therapy", "Safety Measures", "Medications (for specific disorders)"],
    "Recurrent Hypersomnia": ["Cognitive Behavioral Therapy", "Stimulant Medications", "Modafinil"],
    "Persistent Sleep-Related Hypoventilation": ["Continuous Positive Airway Pressure (CPAP)", "Noninvasive Ventilation", "Oxygen Therapy"],
    "Other Sleep Disorders": ["Cognitive Behavioral Therapy", "Medications (for specific symptoms)", "Supportive Therapy"],
    "Sexually Transmitted Infections (STIs)": ["Antibiotics", "Antiviral Medications", "Antifungal Medications"],
    "Chlamydia": ["Azithromycin", "Doxycycline", "Erythromycin"],
    "Gonorrhea": ["Ceftriaxone", "Azithromycin", "Doxycycline"],
    "Syphilis": ["Penicillin", "Doxycycline", "Tetracycline"],
    "Genital Herpes": ["Acyclovir", "Valacyclovir", "Famciclovir"],
    "Genital Warts": ["Podophyllotoxin", "Imiquimod", "Sinecatechins"],
    "Hepatitis B": ["Antiviral Medications", "Interferon", "Vaccination"],
    "Hepatitis C": ["Direct-Acting Antivirals", "Ribavirin", "Interferon"],
    "HIV/AIDS": ["Antiretroviral Therapy", "Pre-exposure Prophylaxis (PrEP)", "Post-exposure Prophylaxis (PEP)"],
    "Human Papillomavirus (HPV)": ["Vaccination", "Cryotherapy", "Electrocautery"],
    "Trichomoniasis": ["Metronidazole", "Tinidazole", "Secnidazole"],
    "Bacterial Vaginosis": ["Metronidazole", "Clindamycin", "Tinidazole"],
    "Yeast Infections": ["Antifungal Medications", "Topical Creams", "Oral Medications"],
    "Pelvic Inflammatory Disease (PID)": ["Antibiotics", "Pain Medications", "Hospitalization"],
    "Genital Candidiasis": ["Antifungal Medications", "Topical Creams", "Oral Medications"],
    "Urinary Tract Infections (UTIs)": ["Antibiotics", "Pain Relievers", "Fluids"],
    "Bladder Infections": ["Antibiotics", "Pain Relievers", "Fluids"],
    "Kidney Infections": ["Antibiotics", "Pain Relievers", "Hospitalization"],
    "Urethritis": ["Antibiotics", "Pain Relievers", "Fluids"],
    "Vaginitis": ["Antifungal Medications", "Topical Creams", "Oral Medications"],
    "Prostatitis": ["Antibiotics", "Pain Relievers", "Alpha-blockers"],
    "Herpes Zoster (Shingles)": ["Antiviral Medications", "Pain Relievers", "Topical Creams"],
    "Varicella (Chickenpox)": ["Antiviral Medications", "Pain Relievers", "Antihistamines"],
    "Measles": ["Supportive Care", "Vitamin A Supplements", "Antibiotics (for secondary infections)"],
    "Mumps": ["Supportive Care", "Pain Relievers", "Fluids"],
    "Rubella (German Measles)": ["Supportive Care", "Pain Relievers", "Antihistamines"],
    "Mononucleosis (Mono)": ["Supportive Care", "Pain Relievers", "Corticosteroids (for severe symptoms)"],
    "Infectious Mononucleosis": ["Supportive Care", "Pain Relievers", "Corticosteroids (for severe symptoms)"],
    "Hand, Foot, and Mouth Disease": ["Supportive Care", "Pain Relievers", "Topical Oral Analgesics"],
    "Scarlet Fever": ["Antibiotics", "Supportive Care", "Pain Relievers"],
    "Roseola": ["Supportive Care", "Pain Relievers", "Antipyretics"],
    "Fifth Disease": ["Supportive Care", "Pain Relievers", "Antipyretics"],
    "Whooping Cough": ["Antibiotics", "Supportive Care", "Pain Relievers"],
    "Croup": ["Steroids", "Nebulized Epinephrine", "Humidified Air"],
    "Respiratory Syncytial Virus (RSV)": ["Supportive Care", "Bronchodilators", "Steroids"],
    "Tuberculosis (TB)": ["Antibiotics", "Directly Observed Therapy (DOT)", "Vaccination"],
    "Hantavirus Pulmonary Syndrome (HPS)": ["Supportive Care", "Extracorporeal Membrane Oxygenation (ECMO)", "Ribavirin"],
    "SARS (Severe Acute Respiratory Syndrome)": ["Supportive Care", "Antiviral Medications", "Corticosteroids"],
    "MERS (Middle East Respiratory Syndrome)": ["Supportive Care", "Antiviral Medications", "Corticosteroids"],
    "COVID-19": ["Antiviral Medications", "Monoclonal Antibodies", "Vaccination"]
};

const diseaseSelect = document.getElementById('diseaseList');
const preventionInfoDiv = document.getElementById('preventionInfo');

function populateDiseaseList() {
  diseaseList.forEach(disease => {
    const optionElement = document.createElement('option');
    optionElement.value = disease;
    optionElement.textContent = disease;
    diseaseSelect.appendChild(optionElement);
  });
}

function displayPreventionInfo() {
  const selectedDisease = diseaseSelect.value;
  const preventionTips = diseaseInfo[selectedDisease];
  preventionInfoDiv.innerHTML = ''; // Clear previous info

  if (preventionTips) {
    preventionInfoDiv.innerHTML = `<h3>Prevention Tips for ${selectedDisease}</h3><ul>`;
    preventionTips.forEach(tip => {
      const listItem = document.createElement('li');
      listItem.textContent = tip;
      preventionInfoDiv.appendChild(listItem);
    });
    preventionInfoDiv.innerHTML += '</ul>';
  } else {
    preventionInfoDiv.innerHTML = '<p>Information on preventing this disease is not currently available.</p>';
  }
}

populateDiseaseList();
diseaseSelect.addEventListener('change', displayPreventionInfo);
